Tentativa de correção do erro 7.
ecomclub/modules-api pull request #10
Opened 2019-08-27 22:10 UTC by IsaqueFernando

Galera, estou enviando para correção para saber se estou construindo pelo caminho certo a solução. Aguardo o retorno.

2019-08-28 00:06 UTC, leomp12 requested changes
o caminho é este sim, mas tem uns erros de sintaxe (sugiro que use um linter pra js no seu editor), também tinha um errinho no endpoint e no body, dá uma olhada se entende minhas sugestões de edição...

2019-08-28 00:06 UTC, leomp12 commented on lib/Checkout/SavePaymentHistory.js
> +    Api(endpointPayment, 'POST', paymentHistoryBody, storeId, err ={
```suggestion
    Api(endpoint, 'POST', paymentHistoryBody, storeId, err => {
```

2019-08-28 00:06 UTC, leomp12 commented on lib/Checkout/SavePaymentHistory.js
> +    paymentHistoryBody = {
```suggestion
    const paymentHistoryBody = {
```

2019-08-28 00:06 UTC, leomp12 commented on lib/Checkout/SavePaymentHistory.js
> +    let endpointPayment = 'orders/' + orderId + '/payment_history.json'
```suggestion
    const endpoint = 'orders/' + orderId + '/payments_history.json'
```

2019-08-28 00:06 UTC, leomp12 commented on lib/Checkout/SavePaymentHistory.js
> +    let endpoint = 'orders/' + orderId + '/transactions.json'
```suggestion
```

2019-08-28 00:06 UTC, leomp12 commented on lib/Checkout/SavePaymentHistory.js
> +        "payment_history.status" : transactionBody.status.current
```js
{
  status: transactionBody.status.current
}
```

2019-09-03 19:11 UTC, leomp12 commented
Fala @IsaqueFernando , vou te pedir desculpas mas eu tive que resolver este issue pra prosseguir nosso desenvolvimento aqui, se tiver interessado dá uma olhada neste commit:
https://github.com/ecomclub/modules-api/commit/9e2591252da73bc2c0ae40820114b03d0e24e842

De qualquer forma, dá um toque no matheus depois...

2019-09-03 19:11 UTC, closed without merging

2019-09-03 19:52 UTC, IsaqueFernando commented
Tranquilo Léo. Eu que preciso me desculpar, agarrado com as tarefas da
faculdade e uma viagem que precisei fazer não consegui olhar a tempo.
Quanto ao Matheus eu aviso sim.

Em ter, 3 de set de 2019 às 16:11, Leonardo Matos <notifications@github.com>
escreveu:

> Fala @IsaqueFernando <https://github.com/IsaqueFernando> , vou te pedir
> desculpas mas eu tive que resolver este issue pra prosseguir nosso
> desenvolvimento aqui, se tiver interessado dá uma olhada neste commit:
> 9e25912
> <https://github.com/ecomclub/modules-api/commit/9e2591252da73bc2c0ae40820114b03d0e24e842>
>
> De qualquer forma, dá um toque no matheus depois...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ecomclub/modules-api/pull/10?email_source=notifications&email_token=ADZUOJDW6RGAEBF353PCDBLQH2ZG5A5CNFSM4IQPGCR2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5ZIENY#issuecomment-527598135>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADZUOJEKLTDID6TW7ZZGTJ3QH2ZG5ANCNFSM4IQPGCRQ>
> .
>