Tentativa de correção do erro 4 para o desafio do estágio.
ecomclub/modules-api pull request #9
Opened 2019-08-24 12:18 UTC by IsaqueFernando

Agurdo o retorno em caso de erro. Muito obrigado galera.

2019-08-24 21:03 UTC, leomp12 requested changes
mandou bem @IsaqueFernando !
só vou te pedir pra remover algumas coisas, e no diminuir também o body que você enviou no patch, colocou mais propriedades que o necessário, na verdade o necessário era apenas `{ status: 'cancelled' }`, mas o `staff_notes` é uma boa ideia, mas o resto não deveria ser alterado neste ponto..

2019-08-24 21:03 UTC, leomp12 commented on commitlint.config.js
> +module.exports = {extends: ['@commitlint/config-angular']};
as convenções do angular são até legais, mas deixa o conventional mesmo por enquanto

```suggestion
module.exports = {extends: ['@commitlint/config-conventional']};
```

2019-08-24 21:03 UTC, leomp12 commented on lib/Checkout/SaveTransaction.js
> +          "current": "invoice_issued"
`invoice_issued` é pra quando a nota fiscal for emitida, não é o caso..

2019-08-24 21:03 UTC, leomp12 commented on lib/Checkout/SaveTransaction.js
> +          "current": "pending"
não conseguimos gerar a transação, então na verdade não tem `financial_status`, é como se ficasse indefinido...

2019-08-24 21:03 UTC, leomp12 commented on lib/Checkout/SaveTransaction.js
> +        "amount": {},
```suggestion
```
isto iria resetar o amount do pedido, não é uma boa ideia..

2019-08-24 21:03 UTC, leomp12 commented on lib/Checkout/SaveTransaction.js
> +        "code": "P05NX",
```suggestion
```
este é um código de referência do pedido, acho que não devemos alterá-lo aqui

2019-08-24 21:03 UTC, leomp12 commented on package.json
> +    "@commitlint/config-angular": "^8.1.0",
```suggestion
```

2019-08-24 21:03 UTC, leomp12 commented on routes/#checkout.js
> +                    'status' // Getting the status.
```suggestion
```
neste ponto a gente está pegando propriedade do body recebido no POST pra montar o data que vamos usar pra criar a transação, correto?
não faz sentido pegar o status aqui, na verdade o status vai ser retornado após a criação da nova transação...

2019-08-24 21:04 UTC, leomp12 commented
mas mandou bem, nem conversamos muito e você pegou a ideia, acho que era o mais importante!

2019-08-25 23:44 UTC, IsaqueFernando commented on lib/Checkout/SaveTransaction.js
> +          "current": "invoice_issued"
Beleza.

2019-08-25 23:45 UTC, IsaqueFernando commented on lib/Checkout/SaveTransaction.js
> +          "current": "pending"
Beleza. Foi o padrão gerado pela doc. Por isso adicionei.

2019-08-25 23:46 UTC, IsaqueFernando commented on routes/#checkout.js
> +                    'status' // Getting the status.
Ok.

2019-08-25 23:49 UTC, IsaqueFernando commented
Léo, as modificações que foram sugeridas e não havia a opção de confirmá-las eu devo modificar localmente e depois fazer um segundo merge request ?

2019-08-26 01:03 UTC, leomp12 commented
É só você editar localmente, comitar e dar push normalmente no mesmo branch, assim como você fez antes do pull request.
Quando você publicar novos commits o github vai atualizar o PR automaticamente.

2019-08-27 19:42 UTC, isaquefms commented
Beleza @leomp12 , fiz isso. Qualquer erro pode me falar.

2019-08-27 20:05 UTC, leomp12 approved these changes

2019-08-27 20:06 UTC, merged